apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gateway
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: gateway

  sourceRepos:
    - "*"

  destinations:
    - namespace: glassdome-gateway-console
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: argocd
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
