apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-app.fullname" . }}
  labels:
    {{- include "gateway-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gateway-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gateway-app.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gateway-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort}}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: mqtt-config
              mountPath: {{ .Values.mqttConfigPath }}
            - name: mqtt-file-queue
              mountPath: {{ .Values.mqttFileQueuePath }}
            - name: mqtt-file-store
              mountPath: {{ .Values.mqttFileStorePath }}
          env:
            - name: MQTT_CONFIG_PATH
              value: {{ .Values.mqttConfigPath }}
            - name: MQTT_FILE_QUEUE_PATH
              value: {{ .Values.mqttFileQueuePath }}
            - name: MQTT_FILE_STORE_PATH
              value: {{ .Values.mqttFileStorePath }}
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: mqtt-config
          hostPath:
            path: {{ .Values.mqttConfigPath }}
        - name: mqtt-file-queue
          hostPath:
            path: {{ .Values.mqttFileQueuePath }}
            type: DirectoryOrCreate
        - name: mqtt-file-store
          hostPath:
            path: {{ .Values.mqttFileStorePath }}
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
