{{- if .Values.ingress.enabled -}}
{{- $fullName := include "glassdome-gateway-console.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "glassdome-gateway-console.labels" . | nindent 4 }}
spec:
  {{- if and .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
{{- end }}
