nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  className: ""
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-console-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-console-web
                port:
                  name: http
