apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh.fullname" . }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
data:
  ssh_private_key: {{ .Values.sshPrivateKey | b64enc }}
type: Opaque
