apiVersion: v1
kind: Service
metadata:
  # name: {{ include "ssh.fullname" . }}
  name: "ssh"
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 2222
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh.selectorLabels" . | nindent 4 }}
