apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  api_private_key: {{ .Values.apiPrivateKey | b64enc }}
  api_public_key: {{ .Values.apiPublicKey | b64enc }}
type: Opaque
